language: php

php:
    - 7.2

env:
    matrix:
#         - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

# script:
#   - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

# after_script:
#   - wget https://scrutinizer-ci.com/ocular.phar
#   - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
